name: Commit linting

on:
  - push

jobs:
  commit-lint:
    name: commit linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: âš™ï¸ prepare environment
        run: |
          sudo apt install -y git curl
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo DEBIAN_FRONTEND=noninteractive apt install -y nodejs

      - name: ğŸ“© install commitlint
        run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

      - name: ğŸ§ª validate last commit
        run: npx commitlint --from HEAD~1 --to HEAD --verbose